-- AlterTable
ALTER TABLE `companion` ADD COLUMN `top10Id` INTEGER NULL;

-- CreateTable
CREATE TABLE `Top10` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Companion` ADD CONSTRAINT `Companion_top10Id_fkey` FOREIGN KEY (`top10Id`) REFERENCES `Top10`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
